// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testdata

import (
	"context"

	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIPgxPool creates a new instance of MockIPgxPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPgxPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPgxPool {
	mock := &MockIPgxPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPgxPool is an autogenerated mock type for the IPgxPool type
type MockIPgxPool struct {
	mock.Mock
}

type MockIPgxPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPgxPool) EXPECT() *MockIPgxPool_Expecter {
	return &MockIPgxPool_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type MockIPgxPool
func (_mock *MockIPgxPool) Begin(ctx context.Context) (pgx.Tx, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 pgx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (pgx.Tx, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) pgx.Tx); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPgxPool_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockIPgxPool_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx
func (_e *MockIPgxPool_Expecter) Begin(ctx interface{}) *MockIPgxPool_Begin_Call {
	return &MockIPgxPool_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockIPgxPool_Begin_Call) Run(run func(ctx context.Context)) *MockIPgxPool_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIPgxPool_Begin_Call) Return(tx pgx.Tx, err error) *MockIPgxPool_Begin_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockIPgxPool_Begin_Call) RunAndReturn(run func(ctx context.Context) (pgx.Tx, error)) *MockIPgxPool_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// BeginTx provides a mock function for the type MockIPgxPool
func (_mock *MockIPgxPool) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	ret := _mock.Called(ctx, txOptions)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 pgx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) (pgx.Tx, error)); ok {
		return returnFunc(ctx, txOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) pgx.Tx); ok {
		r0 = returnFunc(ctx, txOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.TxOptions) error); ok {
		r1 = returnFunc(ctx, txOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPgxPool_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockIPgxPool_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx
//   - txOptions
func (_e *MockIPgxPool_Expecter) BeginTx(ctx interface{}, txOptions interface{}) *MockIPgxPool_BeginTx_Call {
	return &MockIPgxPool_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, txOptions)}
}

func (_c *MockIPgxPool_BeginTx_Call) Run(run func(ctx context.Context, txOptions pgx.TxOptions)) *MockIPgxPool_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.TxOptions))
	})
	return _c
}

func (_c *MockIPgxPool_BeginTx_Call) Return(tx pgx.Tx, err error) *MockIPgxPool_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockIPgxPool_BeginTx_Call) RunAndReturn(run func(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error)) *MockIPgxPool_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}
